name: Security

on:
  workflow_dispatch:    
  pull_request:
    branches: [ master ]   
  push:
    branches: [ "*" ]      

jobs:
  security:
    uses: hamzabouhadadi03/security-workflows/.github/workflows/fastapi-security.yml@main
    with:
      python-version: "3.12"
      project-path: "."